### ISSUE TITLE
Use of Docker downloader

### ISSUE THREAD

**Issue by chriswyatt1** [TreeOfLifeDCC/downloader-utility#1]
Hey,

Thanks for making a great tool to download specific ToL datasets.

Can I get more info with regards to the docker way to do this? I can't seem to find where the files are downloaded. I ran:

`docker run --rm -v "$PWD/download_location:/code/app/download_option" downloader-utility:latest  --phylogeny Amphipyrinae  --experiment_type "Hi-C - Arima v1" --download_option annotations`

Then it says :
```
location is not valid using default location
annotations
Download Started !! http://ftp.ensembl.org/pub/rapid-release/species/Amphipyra_tragopoginis/GCA_905220435.1/geneset/2021_11/Amphipyra_tragopoginis-GCA_905220435.1-2021_11-genes.gff3.gz
Download Started !! http://ftp.ensembl.org/pub/rapid-release/species/Amphipyra_tragopoginis/GCA_905220435.1/geneset/2021_11/Amphipyra_tragopoginis-GCA_905220435.1-2021_11-genes.gtf.gz
Download Started !! http://ftp.ensembl.org/pub/rapid-release/species/Amphipyra_tragopoginis/GCA_905220435.1/geneset/2021_11/Amphipyra_tragopoginis-GCA_905220435.1-2021_11-pep.fa.gz
Download Started !! http://ftp.ensembl.org/pub/rapid-release/species/Amphipyra_tragopoginis/GCA_905220435.1/genome/Amphipyra_tragopoginis-GCA_905220435.1-softmasked.fa.gz
```

Where exactly is it being saved to? What is the default location. Do I need to specify a folder to bind to on my machine?

**Comment by Raheela1024** [comment]
Hi,
 
I think one part of your command need to be changed.

`$PWD/download_location:/code/app/download_option` part of command part should be like `$PWD/download_location:/code/app/annotations`.

It will save data into you folder with the name of annotations that is `download_option` variable.
As we are running docker image if we don’t provide the location or not change the command as mentioned it will save data into docker container.

**Comment by chriswyatt1** [comment]
Thanks, that's great, it's running fine now.  Sorry, just my lack of understanding.
 
I have some other little issues (please no rush answering, I can play around to work it out, esp Friday evening :) ), e.g. I think --experiment_type is not optional, at least when running (without specifying --experiment_type):
`docker run --rm -v "$PWD/download_location:/code/app/annotations" downloader-utility:latest --phylogeny Hymenoptera  --download_option annotations`

It would be nice then to be able to download any of the experiment types of a particular phylogenetic level, as I was worried at first as only three species downloaded in the above search, but this was just because of the `--experiment_type "Hi-C - Arima v1"` filter. 

Thanks, looking forward to using it more

**Comment by Raheela1024** [comment]
Currently if you provide `experiment_type` empty then it i will work but i updated the code if `experiment_type` is none it will download all species data.

`downloader-utility-main % docker run --rm -v "$PWD/download_location:/code/app/annotations" downloader-utility:latest --phylogeny Hymenoptera --download_option annotations`

Please try with latest pull if you still feel issue let me know.

**Comment by chriswyatt1** [comment]
Awesome thanks!

**Comment by chriswyatt1** [comment]
Sorry to bother again.

I am getting some files with no content.

When running the following:
`docker run --rm -v "$PWD/download_location:/code/app/annotations" downloader-utility:latest --phylogeny Hymenoptera  --download_option annotations --experiment_type "Hi-C - Arima v2"`

I get no entry for some of the species (see all the ones with 199B):

```
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:09 Seladonia_tumulorum-GCA_913789895.3-softmasked.fa.gz
drwxr-xr-x  39 cwyatt  staff   1.2K Sep 20 18:09 .
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:09 Bombus_terrestris-GCA_910591885.2-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    87M Sep 20 18:09 Bombus_terrestris-GCA_910591885.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    75M Sep 20 18:08 Bombus_terrestris-GCA_000214255.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    82M Sep 20 18:08 Bombus_hortorum-GCA_905332935.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    57M Sep 20 18:07 Vespula_vulgaris-GCA_905475345.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    82M Sep 20 18:07 Bombus_pascuorum-GCA_905332965.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:06 Vespa_crabro-GCA_910589235.2-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:06 Sphecodes_monilicornis-GCA_913789915.3-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:06 Dolichovespula_saxonica-GCA_911387935.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   121M Sep 20 18:06 Cerceris_rybyensis-GCA_910591515.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    81M Sep 20 18:05 Bombus_sylvestris-GCA_911622165.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:05 Anoplius_nigerrimus-GCA_914767735.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    69M Sep 20 18:05 Ancistrocerus_nigricornis-GCA_916049575.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff    95M Sep 20 18:04 Andrena_haemorrhoa-GCA_910592295.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   130M Sep 20 18:04 Macropis_europaea-GCA_916610135.1-softmasked.fa.gz
-rw-r--r--   1 cwyatt  staff   199B Sep 20 18:03 Andrena_minutula-GCA_929113495.1-softmasked.fa.gz
```

When I cat them, I get:

```
cat download_location/softmaskedGenome/Bombus_terrestris-GCA_910591885.2-softmasked.fa.gz

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>

```

In the finder, I see that there is no softmasked genome in the ftp site, so it explains why it is not in the output :

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/9978862/191310570-9d3bdfd3-a5af-4625-9ff3-561398045422.png">

**Comment by chriswyatt1** [comment]
Is there a way to get the chromosomes.tsv.gz file through the downloader tool?. No problem if not, I could manually download these ones

**Comment by Raheela1024** [comment]
@chriswyatt1  Unfortunately currently we Cann’t get a specific file using only file name basis using this utility.

**Comment by chriswyatt1** [comment]
I realised that actually the genomes that are called e.g. Bombus_terrestris-GCA_910591885.2-**chromosomes.**tsv.gz e.g. the one mentioned above, are not actually present. Is this due to them not being ready for release or is the file corrupted maybe? As in there is a GFF3 file that looks normal, but the (non soft masked genome) with chromosomes in the name are empty

**Comment by Raheela1024** [comment]
@chriswyatt1 can you share you command that you use to run for getting data i can verify from the server .

**Comment by chriswyatt1** [comment]
@Raheela1024 I think this is a database not the tool issue.

e.g. If you go to https://portal.darwintreeoflife.org/data/root/details/Athalia%20rosae 

You cannot download the genome using the link (http://ftp.ensembl.org/pub/rapid-release/species/Athalia_rosae/GCA_917208135.1/genome/Athalia_rosae-GCA_917208135.1-softmasked.fa.gz), or by the downloader tool. 

This is because there is no genome uploaded, the one on the portal is called 

`http://ftp.ensembl.org/pub/rapid-release/species/Athalia_rosae/GCA_917208135.1/genome/Athalia_rosae-GCA_917208135.1-chromosomes.tsv.gz`. Which has no content.

**Comment by chriswyatt1** [comment]
It does say :
<img width="410" alt="image" src="https://user-images.githubusercontent.com/9978862/192288176-56157185-8255-41ba-ac39-2aabd58e2f2b.png">  , but maybe these ones have not been uploaded yet.

This is the same for around 10 species in the hymenoptera.

**Comment by Raheela1024** [comment]
@chriswyatt1 yes i think data is not uploaded for them bcoz i try to download from server its same no data for chromosome in fasta file.
I will check that and come back to you.

**Comment by chriswyatt1** [comment]
Awesome, thanks :)

**Comment by Raheela1024** [comment]
@chriswyatt1 i just checked if i go http://ftp.ensembl.org/pub/rapid-release/species/Athalia_rosae/GCA_917208135.1/genome/Athalia_rosae-GCA_917208135.1-chromosomes.tsv.gz this file has content. You mentioned the issue regarding genome you are unable to download data we are looking into.
<img width="148" alt="Screenshot 2022-09-26 at 15 56 45" src="https://user-images.githubusercontent.com/32760007/192310483-e045522f-e4c9-433b-931f-afa42796e104.png">

**Comment by Raheela1024** [comment]
@chriswyatt1 genome (http://ftp.ensembl.org/pub/rapid-release/species/Athalia_rosae/GCA_917208135.1/genome/Athalia_rosae-GCA_917208135.1-softmasked.fa.gz) file is downloadable now. can you try and face issue again let me know.

**Comment by Raheelaaslam1024** [comment]
I think everything is working fine and no new comment so closing the issue.
